language: go

os:
  - linux

env:
  - GO111MODULE=on

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - tip

matrix:
  allow_failures:
    - go: tip

# Don't email me the results of the test runs.

notifications:
  email: false
#  email:
#    on_success: change
#    on_failure: always

install:
  - go get -d

script:
  - go test -bench=. -benchmem -cpu 1,4,8 -benchtime 10s -count 1